org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

# Properties that are commented out must be manually set on each file
mod.group=com.avatarkage
mod.id=enderpearlsreworked
mod.name=Ender Pearls Reworked
mod.version=1.0.2
# mod.authors=AvatarKage
# mod.credits=
mod.description=Reworks the Ender Pearl mechanic, giving you complete control over how and when you teleport.
# mod.displayURL=https://avatarkage.com/projects/minecraft/mods/${id}
# mod.sourceURL=https://github.com/avatarkage/${id}
# mod.issuesURL=https://github.com/avatarkage/${id}/issues
# mod.license=Copyright (c) 2026 AvatarKage. All rights reserved. This modification is not an official Minecraft product and is not approved by or associated with Mojang or its affiliates. For more information, see: https://avatarka.ge/legal.
